# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Backend CI (Go)

on:
  pull_request:
    paths:
      - 'gocommon/**'
      - 'backend/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
 build_backend:
    name: Backend Build and Test (Go)
    permissions:
      contents: read
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v5

    - name: Set up Go (1.24.0)
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.0'
        check-latest: true
        cache-dependency-path: ./backend/go.sum
    
    - name: Build Backend
      working-directory: ./backend
      run: go build -v

    - name: Test Backend
      working-directory: ./backend
      run: go test -v ./...